#!/usr/bin/env python3
"""
Compile all PTX test cases to hex files for RalphGPU testbench
"""

import os
import sys
import subprocess
from pathlib import Path

# Add tools directory to path
SCRIPT_DIR = Path(__file__).parent.absolute()
PROJECT_ROOT = SCRIPT_DIR.parent
TOOLS_DIR = PROJECT_ROOT / "tools"
sys.path.insert(0, str(TOOLS_DIR))

from ptx_assembler import assemble_file

def compile_all_tests():
    """Compile all PTX tests in the comprehensive tests directory"""

    ptx_dir = PROJECT_ROOT / "asm" / "ptx_comprehensive_tests"
    hex_dir = PROJECT_ROOT / "hex" / "ptx_comprehensive_tests"

    # Create output directory
    hex_dir.mkdir(parents=True, exist_ok=True)

    # Find all PTX files
    ptx_files = sorted(ptx_dir.glob("*.ptx"))

    print(f"Found {len(ptx_files)} PTX test files")
    print(f"Output directory: {hex_dir}")
    print("-" * 60)

    success_count = 0
    fail_count = 0
    results = []

    for ptx_file in ptx_files:
        hex_file = hex_dir / (ptx_file.stem + ".hex")

        try:
            # Assemble PTX to hex
            machine_code = assemble_file(str(ptx_file), str(hex_file))

            # Count instructions
            instr_count = len(machine_code)

            print(f"[OK] {ptx_file.name} -> {hex_file.name} ({instr_count} instructions)")
            results.append({
                'name': ptx_file.stem,
                'ptx_file': str(ptx_file),
                'hex_file': str(hex_file),
                'instructions': instr_count,
                'status': 'OK'
            })
            success_count += 1

        except Exception as e:
            print(f"[FAIL] {ptx_file.name}: {e}")
            results.append({
                'name': ptx_file.stem,
                'ptx_file': str(ptx_file),
                'hex_file': str(hex_file),
                'instructions': 0,
                'status': f'FAIL: {e}'
            })
            fail_count += 1

    print("-" * 60)
    print(f"Compilation complete: {success_count} succeeded, {fail_count} failed")

    # Generate test list file for testbench
    test_list_file = hex_dir / "test_list.txt"
    with open(test_list_file, 'w') as f:
        f.write(f"# RalphGPU PTX Comprehensive Test List\n")
        f.write(f"# Total tests: {len(results)}\n")
        f.write(f"# Generated by compile_ptx_tests.py\n")
        f.write(f"#\n")
        f.write(f"# Format: test_name hex_file instruction_count status\n")
        f.write(f"#\n")
        for r in results:
            f.write(f"{r['name']} {r['hex_file']} {r['instructions']} {r['status']}\n")

    print(f"Test list written to: {test_list_file}")

    return success_count, fail_count, results

if __name__ == '__main__':
    success, fail, results = compile_all_tests()
    sys.exit(0 if fail == 0 else 1)
